version: 2
updates:
  # Backend dependencies - Actualizaciones diarias para seguridad
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 20
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "🔒 deps"
      prefix-development: "🛠️ deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "security"
    groups:
      security-updates:
        applies-to: security-updates
        update-types:
          - "patch"
          - "minor"
      express-ecosystem:
        patterns:
          - "express"
          - "express-*"
        update-types:
          - "patch"
          - "minor"
      database-drivers:
        patterns:
          - "mongoose"
          - "mongodb"
          - "redis"
        update-types:
          - "patch"
          - "minor"
      security-middleware:
        patterns:
          - "helmet"
          - "express-rate-limit"
          - "express-validator"
          - "cors"
        update-types:
          - "patch"
          - "minor"
    ignore:
      - dependency-name: "mongoose"
        versions: ["8.x"] # Solo permitir 7.x por ahora
      - dependency-name: "express"
        versions: ["5.x"] # Express 5 tiene breaking changes
      - dependency-name: "node"
        versions: ["19.x", "21.x"] # Mantener LTS

  # Frontend dependencies - Actualizaciones diarias
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 20
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "🎨 deps"
      prefix-development: "🛠️ deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "security"
    groups:
      security-updates:
        applies-to: security-updates
        update-types:
          - "patch"
          - "minor"
      react-ecosystem:
        patterns:
          - "react"
          - "react-dom"
          - "react-router*"
        update-types:
          - "patch"
          - "minor"
      ui-libraries:
        patterns:
          - "@mui/*"
          - "@emotion/*"
          - "material-ui*"
        update-types:
          - "patch"
          - "minor"
      build-tools:
        patterns:
          - "webpack"
          - "babel-*"
          - "eslint*"
          - "prettier"
        update-types:
          - "patch"
          - "minor"
    ignore:
      - dependency-name: "react"
        versions: ["19.x"] # React 19 tiene cambios significativos
      - dependency-name: "react-dom"
        versions: ["19.x"]
      - dependency-name: "@mui/material"
        versions: ["6.x"] # Mantener v5 por estabilidad

  # GitHub Actions - Actualizaciones semanales
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "08:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 10
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "🤖 ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci/cd"
      - "automation"
    groups:
      security-actions:
        patterns:
          - "actions/*security*"
          - "github/*security*"
          - "azure/*security*"
        update-types:
          - "patch"
          - "minor"
      docker-actions:
        patterns:
          - "docker/*"
          - "*docker*"
        update-types:
          - "patch"
          - "minor"
      azure-actions:
        patterns:
          - "azure/*"
        update-types:
          - "patch"
          - "minor"

  # Docker base images - Actualizaciones semanales
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "🐳 docker"
    labels:
      - "docker"
      - "backend"
      - "security"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:30"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "🐳 docker"
    labels:
      - "docker"
      - "frontend"
      - "security"

  # Dependabot configuration file itself
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "🔧 dependabot"
    labels:
      - "dependabot"
      - "configuration"
      - "automation"